### ISSUE TITLE
add a Room Envelope attribute for optional messages

### ISSUE THREAD

**Issue by michaelplutovr** [aardvarkxr/aardvark#100]
This will help indicate what messsages could be dropped or throttled to handle high load on the relay. Default should be required since most message are. Right now the only optional message is poseUpdate

**Comment by JoeLudwig** [comment]
I think this should be either:
* "routingFlags", which is a bitfield that currently only has one valid bit: WillRetransmit
* or just a bool called willRetransmit.

I'm leaning toward the flags so that future booleans don't need to make the messages any bigger.

**Comment by fuag15** [comment]
+1 for bit field / flags too
