### ISSUE TITLE
Documentation for AvGrabbable, AvSphere/ModelBoxHandle and other nodes

### ISSUE THREAD

**Issue by MichaelHazani** [aardvarkxr/aardvark#103]
as discussed on Slack - when files export multiple components those don't all get included in the autogenerated docs. As the main source of truth, would be great if the "[Aardvark-React Style Guide](https://aardvarkxr.github.io/aardvark/aardvark-react/)" included all available nodes.

**Comment by JoeLudwig** [comment]
The documentation should be complete now: https://aardvarkxr.github.io/aardvark/aardvark-react/index.html

This isn't using react styleguidist anymore so it doesn't specifically generate react-styled documentation. On the other hand, it includes all the classes even if there's more than one in the file.

Can always revisit this down the road when somebody wants to spend more time on doc generation.
