### ISSUE TITLE
Print Error when failing to start server on correct Port

### ISSUE THREAD

**Issue by forestgibson** [aardvarkxr/aardvark#106]
When Aardvark fails to start the server on the correct port, it should throw an error that states this instead of randomly selecting a new port.

**Comment by JoeLudwig** [comment]
"fails to start on correct port" here is because the port was occupied by another process.  Startup should just fail cleanly in that case instead of looking like things are running, but leaving them in broken state.

**Comment by JoeLudwig** [comment]
Renamed the server to aardvark_server.exe, and now the client will kill it when starting up.
