### ISSUE TITLE
avrenderer.exe crashes without output when executed

### ISSUE THREAD

**Issue by marmily** [aardvarkxr/aardvark#117]
When attempting to run avrenderer.exe from a freshly unzipped released build (tested with 0.7.1 and 0.8.1), the application crashes immediately, leaving the http://Node.js instance running and listening on port 23842. 

The application appears to die before the expected avrenderer window would normally appear. Checking the application logs, aardvark.txt only shows the following with each attempted execution (killing http://Node.js manually before each attempt):

2020-05-21 15:53:28,476 INFO Starting browser process
2020-05-21 15:53:28,788 INFO Server started with PID <PID>

Both debug.log and myeasylog.log are empty. I've verified that all device drivers are current, and this behavior occurs both launching aadvark before SteamVR and SteamVR before aardvark.

Any guidance on where to proceed further with this would be greatly appreciated.

**Comment by JoeLudwig** [comment]
I have not been able to reproduce this problem. If you run avrenderer.exe under a debugger are you able to capture a crash dump for wherever it crashes?

Otherwise this might need to wait for #54

**Comment by marmily** [comment]
Hey Joe,

Thanks for the suggestion! I was able to coax out a weird permissions issue during the debug process - specifically I pulled down aardvark as one user but my machine was attempting to run it under another w/o relevant permissions. After resolving this, I have been able to run aardvark without any issues!
