### ISSUE TITLE
When distance interacting, the cursor on the 2d plane doesn't line up with the ray

### ISSUE THREAD

**Issue by JaredMonkey** [aardvarkxr/aardvark#121]
It is very cool to interact with gadgets from afar. The ray that is used for manipulating gadgets, and the underlying 2d cursor on the panel don't line up though. I would like to be able to input into a panel with the same ray.

**Comment by JaredMonkey** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/356520/85928164-cda88a00-b85f-11ea-8156-fd2950a64f95.gif)

**Comment by JoeLudwig** [comment]
This is fixed in 0.14.0. 

This one took some doing. :)
