### ISSUE TITLE
cors parsing isn't working for menu gadget

### ISSUE THREAD

**Issue by michaelplutovr** [aardvarkxr/aardvark#122]
when hosting on local host with something like

`http-server <dir> -p <port> --cors`

I'm getting this message from the menu gadget

`Access to XMLHttpRequest at 'http://localhost:12883/models/placeholder.glb' from origin 'http://localhost:23842' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: http://localhost:23842/gadgets/aardvark_renderer/index.html`

however

`$ curl -v http://localhost:12883/models/placeholder.glb
*   Trying ::1:12883...
*   Trying 127.0.0.1:12883...
* Connected to localhost (127.0.0.1) port 12883 (#0)
> GET /models/placeholder.glb HTTP/1.1
> Host: localhost:12883
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< access-control-allow-origin: *
< access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Range
< server: ecstatic-3.3.2
< cache-control: max-age=3600
< last-modified: Thu, 02 Jul 2020 01:01:51 GMT
< etag: W/"19703248369851876-9608-2020-07-02T01:01:51.886Z"
< content-length: 9608
< content-type: model/gltf-binary; charset=utf-8
< Date: Thu, 02 Jul 2020 01:31:38 GMT
< Connection: keep-alive
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 9608)
* Closing connection 0`

**Comment by michaelplutovr** [comment]
realized this might be a cached request in cef cache with a ttl of an hour from when the server didn't have cors headers. Going to retry in an hour and disable caching on the server and will update this

**Comment by michaelplutovr** [comment]
yep, it was cached in cef somewhere

**Comment by JoeLudwig** [comment]
Yeah, I'm pretty sure I've run into exactly the same thing.
