### ISSUE TITLE
GLB's don't show up for gadgets favorited

### ISSUE THREAD

**Issue by michaelplutovr** [aardvarkxr/aardvark#129]
expected:

when a gadget is favorited, its icon shows up in favorites

observed:

when a gadget is favorited, it is in the favorites but there is no model, only collision, hovering over the place where the model should be with a controller intersects the icon but no icon is displayed. Grabbing this volume and pulling it out will load the correct gadget

**Comment by JoeLudwig** [comment]
I know this is true for the Pluto gadget. Have you also seen it for other gadgets? I have some favorites that have their models showing up...

**Comment by JoeLudwig** [comment]
The pluto gadget has this URL for its icon: 
```
"src": "http://localhost:12883/models/placeholder.glb",
```

I'm not running a webserver locally on that port, so the request fails. Is that something Pluto is expected to run?

**Comment by JoeLudwig** [comment]
Actually I just ran Pluto and it doesn't seem to have a server there either. Maybe this is just a bug from whomever wrote the manifest file for that gadget?

**Comment by michaelplutovr** [comment]
Hey, sorry I left this up here without a response. Yes this seems to be that manifests need to be per release or wherever it is hosted. Is it possible to allow relative paths to icons in a manifest or is this already possible? We're fixing the build on our end, this might resolve the favorites issues as well that were seeing in the DefaultLanding page

**Comment by JoeLudwig** [comment]
Relative paths are already supported. They're relative to the directory that contains the manifest file itself. So in this case it just needs to be models/placeholder.glb.

Sounds like I can close this one. Let me know if you still think there's a bug in Aardvark itself.
