### ISSUE TITLE
existing gadgets dont show up in init universe

### ISSUE THREAD

**Issue by michaelplutovr** [aardvarkxr/aardvark#135]
If a universe was made, then destroyed then remade, the new one will not have any existing gadgets registered with it when asking for the init universe blob.

**Comment by michaelplutovr** [comment]
Sometimes when accessing a local universes (NetworkUniverse) .initInfo, gadgets that were created since the universe was made sometimes do not show up and instead a blank initInfo is used. will try to get more info tomorrow with a repro

**Comment by zweigh** [comment]
@michaelplutovr Did the info get surfaced from the above comment?

**Comment by michaelplutovr** [comment]
Closing this as it doesn't repro with the latest (0.12.0) release of aardvark
