### ISSUE TITLE
DefaultLanding when loaded in a browser claims it cannot find the manifest file

### ISSUE THREAD

**Issue by michaelplutovr** [aardvarkxr/aardvark#138]
This repro's for all gadets shipped with aardvark 0.10.3 for me. It results in a broken DefaultLanding component with just the error message.

**Comment by JoeLudwig** [comment]
Can you provide an example URL? I assume Aardvark was running when it failed, so the webserver was up and all that...

**Comment by JoeLudwig** [comment]
Working fine for me for the builtin stuff. Can you provide a URL that isn't working?

![image](https://user-images.githubusercontent.com/303656/89369509-25be8180-d693-11ea-9eb4-c587e7ebd8bf.png)

**Comment by michaelplutovr** [comment]
http://aardvark-beta.pluto-api.com

**Comment by michaelplutovr** [comment]
Checked and this is still an issue with aardvark-shared 0.12.0, aardvark-react 0.12.0 hasn't shown up yet so perhaps there was a build error in it? I would guess aardvark-react 0.12.0 is where the fix is

`GET http://aardvark-beta.pluto-api.com//manifest.webmanifest`
