### ISSUE TITLE
Aardvark and its gadgets "crash" and become unresponsive

### ISSUE THREAD

**Issue by alandao** [aardvarkxr/aardvark#155]
There are probably multiple bugs being described in this issue report, but anyway, I'll report them here. I've been messing around with the sample gadget in https://www.npmjs.com/package/@aardvarkxr/aardvark-react and I noticed that when I swap holding the gadget between my hands more than a few times, the gadget and/or Aardvark will stop accepting input. I'm forced to kill Aardvark from Task Manager and restart

**Comment by JoeLudwig** [comment]
Is this the thing where the hand spheres turned yellow and then didn't work anymore?

Are you still seeing this?

**Comment by JoeLudwig** [comment]
I think this one was fixed a while back.
