### ISSUE TITLE
Suggestion: Let an AvPanel be projected on any arbitrary mesh that has UV coordinates

### ISSUE THREAD

**Issue by BOLL7708** [aardvarkxr/aardvark#162]
### Description
Have the browser texture being something we can apply to any mesh with a UV map.

### Reasoning
Considering we right now have browser content projected on a quad, it feels like it could be possible to pipe this texture to any mesh instead, mapping it to the existing UV map. 

This would be a nice feature to make curved projection screens, multiple panels from a single browser page or any other non-quad page display that is needed. 

Myself I want to wrap a webpage all around me as an environment.

**Comment by JoeLudwig** [comment]
I think this is already possible.

AvPanel is implemented entirely in the gadget with AvInterfaceEntity and AvModel. If you set the flags on a model to use the browser texture it should work for any textured model, not just planes.

Actually interacting with that model as a panel is harder. That's more of a volume intersection question. But displaying a web page should be supported.

**Comment by BOLL7708** [comment]
Ooooh, I had a small suspicion this could be the case, but wasn't sure. I've honestly not come far enough to even doodle around with the scene graph, I'm still just hacking around the panel alone 😅 I'll keep this in mind and revisit if I can't manage it when I get to it 😗
