### ISSUE TITLE
XR Seattle Podcast

### ISSUE THREAD

**Issue by VRARA-Seattle** [aardvarkxr/aardvark#163]
I wasn't able to attend the hackathon, I hope it went really well.

I'm [Kirby Shabaga](https://www.linkedin.com/in/kirbyshabaga), one of the [XR Seattle Podcast](https://anchor.fm/xrseapod) team.  I think it would be valuable to have one or two of the hackathon attendees and/or organizers join us for a conversation.  In the past, we have had episodes on hackathons, eye tracking, and most recently interviewed HaptX.

If anyone is interested, please contact me at Kirby@TankAndDozer.com

Thank you!

**Comment by JoeLudwig** [comment]
I'd be happy to chat. I'll shoot you an email. 

Slack or email are better forums for this kind of conversation, so I'm going to go ahead and close this issue.
