### ISSUE TITLE
Skinned animated mesh doesn't load or display properly

### ISSUE THREAD

**Issue by JaredMonkey** [aardvarkxr/aardvark#171]
I attempted to load: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedSimple

It looks like this:

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/356520/101193048-d6706980-3610-11eb-99e5-4a74b08a54f4.gif)

**Comment by JoeLudwig** [comment]
This is fixed in head, at least for the model I had that was demonstrating a similar problem.

**Comment by JoeLudwig** [comment]
I ran into more problems with the hands, and tried this model. It still didn't work. So probably not fixed.
