### ISSUE TITLE
Trigger for right hand does not interact with steam when Aardvark is on. 

### ISSUE THREAD

**Issue by zweigh** [aardvarkxr/aardvark#172]
When using Steam VR, I normally am able to use my right-hand trigger to select items in the steam dashboard. When I start Aadrvark, I lose that ability. I would expect Aardvark to not affect my ability to use Steam dashboard.

**Comment by JoeLudwig** [comment]
Thanks for the report. There's a fix in the next build of Aardvark (and another "overlay apps may not do that" fix in a future version of SteamVR.)

**Comment by JoeLudwig** [comment]
Fixed in 1.4.2
