### ISSUE TITLE
Networked Universii with initInfo that contain remote gadgets spawned too close to the start of a rooms gadget break in a way that causes the remote gadgets to terminate

### ISSUE THREAD

**Issue by michaelplutovr** [aardvarkxr/aardvark#173]
### Scenario

- Users A, B are in a conversation using the rooms gadget and all have gadgets out.

- User C enters the room and immediately recieves room information from the network containing information about the remote universii along with their initInfo which at this point contains a gadget. Around the first frame, the rooms gadget of C instantiates and renders a remote universe with the provided init info.

- In this scenario the remote gadets dies and user C is left in a broken state.

### Reproduction steps

Make a rooms gadget that spawns a remote universe immediately with the init info below.

```
{
    gadgets: [
      {
        url: "https://sophiabaldonado.github.io/mood",
        remoteLocks: [
          {
            iface: "test_panel_counter@1",
            receiver: { type: EndpointType.Unknown },
            params: { imgPath: 24 },
          },
        ],
        universeFromGadget: [
          0.03521648049354553,
          1.491823434829712,
          -1.485067367553711,
          -0.41708019375801086,
          -0.2775963246822357,
          0.8493847846984863,
          -0.16592732071876526,
        ],
        remoteGadgetId: 1,
        items: [],
      },
    ],
  };
```

__NOTE: over the wire receiver comes thorugh as null, the EndpointType.Unknown was added to make typsecript happy and should have no affect as for remote universii initInfo gadgets the receiver is ignored.__

### Known oddities

1. The below is output by the gadgets window on first render

```
aardvark_gadget.tsx?4bb6:301 Received interface start for N:42:1->N:30:660(aardvark-container@1)
component_moveable.ts?e7d7:250 Redrop request to replace N:30:656
aardvark_gadget.tsx?4bb6:301 Received interface start for N:42:1->N:28:27(aardvark-container@1)
component_moveable.ts?e7d7:280 got new container N:28:27 while waiting for redrop
```

2. The child gadget does appear briefly and then segfaults or is terminated, unknown as logs are not available afaik

3. If extra log statements are added to the server the remote universes gadget can be seen coming online with an endpoint address of 0 but a valid nodeId, it gets roughly 3 messages attempting to be routed to this address and then is terminated and or dies.

__NOTE: at the point that all of this happens, the room gadget itself is assigned an enpoint and a node id that are valid__

### Open questions

- Is the redrop while dropping a problem, not sure if this is logged as an indication of an error or simply info logging.
- Is the universe coming up intitially with an enpoint that doesn't exist an issue or intended
- How does a gadget initially get assigned an endpoint in the happy use case
- What is the intent for assigning endpoints to child gadgets of networked universii

**Comment by fuag15** [comment]
After more investigation and help from @JoeLudwig the issue was that gadget stuff was getting rendered before the gadget had finished its initial handshake with the local server. 

Modifying the rooms gadget to use waitForConnect from https://github.com/aardvarkxr/aardvark/pull/174 resolves the issue.
