### ISSUE TITLE
Can't trigger palette on original VIVE

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [aardvarkxr/aardvark#175]
On the (I think) original VIVE here, I can see the orange gear and two gray geodesics, and the gear enlarges and I get a haptic click when I bring my controllers together, but the triggers don't seem to do anything.  (None of the other controls bring up the chooser either.)  Too old?  I can send debug information and/or build here.

**Comment by JoeLudwig** [comment]
Yes, Brad. You're too old. :)

Probably Vive classic bindings are just missing. What version of Aardvark are you running?

**Comment by bradgrantham-lunarg** [comment]
Yeah, well, that's increasingly true...

1.4.1, installed yesterday.

**Comment by JoeLudwig** [comment]
Yeah, it looks like I just didn't include Vive bindings. I'll fix that for the next build. Probably this evening.
