### ISSUE TITLE
In Steam, 'Exit Game' doesn't close Aardvark

### ISSUE THREAD

**Issue by JaredMonkey** [aardvarkxr/aardvark#177]
As a user, I would expect the exit button to work in the Steam release. It may also be good to config the app in Steam to not say 'game'

**Comment by JaredMonkey** [comment]
![image](https://user-images.githubusercontent.com/356520/103490933-28550c80-4dd4-11eb-9e72-9de9c831a88b.png)

**Comment by JaredMonkey** [comment]
The 'X STOP' button in the desktop UI doesn't work either 
![image](https://user-images.githubusercontent.com/356520/103490943-43c01780-4dd4-11eb-9bd4-cd3c55dc05b9.png)

**Comment by JoeLudwig** [comment]
Fixed in 1.5.4. More importantly, the same bug was preventing Aardvark from closing when SteamVR exited.
