### ISSUE TITLE
Aardvark is unresponsive when an asset isn't able to be loaded

### ISSUE THREAD

**Issue by JaredMonkey** [aardvarkxr/aardvark#181]
I'm able to repro this on my machine when an asset isn't able to be loaded (like if I've started my server without the correct CORS flags on my local dev environment) like a GLB.

Aardvark will go unresponsive, and if I hover over the scanner, I'll get haptic events that fire whenever I'm intersecting the scanner.

**Comment by JoeLudwig** [comment]
What context did you have an invalid model in?

**Comment by JoeLudwig** [comment]
Possibly fixed in 1.5.4? If it's still happening, let me know what node type has the bogus URL and I can get that one fixed up too.

**Comment by JaredMonkey** [comment]
Tested in 1.5.4. Confirmed fixed!
