### ISSUE TITLE
Gadget toolbox UI is terrible

### ISSUE THREAD

**Issue by JoeLudwig** [aardvarkxr/aardvark#24]
- [x] Gadgets collide with each other
- [x] The "I'm in range" indicator of increasing the scale is hard to see on many gadgets
- [x] Gadget "icons" are all different sizes
- [x] Gadget names don't appear anywhere
- [ ] There's no way to remove a gadget from the list once it appears there
- [x] The scroll thumb (if that's even the right metaphor) is too small

**Comment by JaredMonkey** [comment]
ScaleToFit works well.

![image](https://user-images.githubusercontent.com/356520/70950185-bc5f0500-2014-11ea-958d-f5bc807b0c9f.png)

**Comment by JoeLudwig** [comment]
Are you still thinking about this, or should we unassign it?

**Comment by JoeLudwig** [comment]
Gadget menu has been completely replaced, and most of these issues are better. If there are any issues with the new one (which seems likely), we should open a new Github issue to track it.
