### ISSUE TITLE
Need a way to install a gadget from a desktop web browser

### ISSUE THREAD

**Issue by JoeLudwig** [aardvarkxr/aardvark#51]
aardvark://install URL handler? Websocket request from the browser to the server while Aardvark is running? little file you download and run with a known extension?

Whatever the solution is, users shouldn't be forced to run "avcmd install <url>" to install a gadget.

**Comment by JaredMonkey** [comment]
Maybe the PWA concept “Add to Homescreen” (A2HS) could also make sense?

https://developers.google.com/web/updates/2018/06/a2hs-updates

**Comment by JoeLudwig** [comment]
Something like that certainly works when the user is browsing through Aardvark itself. That could be pretty slick.

What I'm mainly after here is a way for the user's desktop browser to install a gadget. I have a URL handler working on a branch. Just need to add support for the aardvark://install/ sub-url and it should be good to go.
