### ISSUE TITLE
Hands are in the wrong place

### ISSUE THREAD

**Issue by JoeLudwig** [aardvarkxr/aardvark#65]
![image](https://user-images.githubusercontent.com/303656/71560468-2b7a2780-2a1f-11ea-8012-b5bdace3a192.png)

The controllers drawn by SteamVR are drawn where Lighthouse thinks the controllers are. The blue balls are drawn at the "tip" pose using those same controller positions. That should be right at the front of the controllers pointing forward, not floating a few cm above the controllers. This is a pretty significant usability hassle because the user has to "move the blue ball over there" instead of "move my hand over there".

I suspect this is Varggles-related. Maybe the projection onto the latlong map is wrong? Maybe it's not possible to match the underlying world exactly? The offset between the two seems to move around as you turn your head.

**Comment by JoeLudwig** [comment]
@JaredMonkey Any idea what might be happening?

**Comment by JaredMonkey** [comment]
In other projects, the Varggles implementation is lined up with what renders normally. At first glance, the only difference I see is that in other implementations the the eyes positioned based on half of IPD returned by OpenVR. Maybe that could be related? I think we had just re-used the eye pose setups from the previous eye buffers. I'll have a look.

**Comment by JoeLudwig** [comment]
What is the -1m Z offset in the matrix all about? Seems like a latlong panorama would ignore the translation in any case, but why 1m?

https://github.com/aardvarkxr/aardvark/blob/ac7bc44d8af54553abc42f39917b43464af7ae2c/src/avrenderer/vrmanager.h#L58

**Comment by JoeLudwig** [comment]
Looks like the right/left eyes from GetEyeToHeadTransform are exactly the same as what you would get if you built the matrix yourself using half the IPD:
![image](https://user-images.githubusercontent.com/303656/71628572-79249a80-2bad-11ea-8d1f-05bc0b7740a4.png)

`	float fIpd = vr::VRSystem()->GetFloatTrackedDeviceProperty(vr::k_unTrackedDeviceIndex_Hmd, vr::Prop_UserIpdMeters_Float);
	vr::HmdMatrix34_t matEyeRight = vr::VRSystem()->GetEyeToHeadTransform( nEye );
	glm::mat4 matrixObj(
		matEyeRight.m[0][0], matEyeRight.m[1][0], matEyeRight.m[2][0], 0.0,
		matEyeRight.m[0][1], matEyeRight.m[1][1], matEyeRight.m[2][1], 0.0,
		matEyeRight.m[0][2], matEyeRight.m[1][2], matEyeRight.m[2][2], 0.0,
		matEyeRight.m[0][3], matEyeRight.m[1][3], matEyeRight.m[2][3], 1.0f
	);
`

**Comment by fuag15** [comment]
> 
> 
> What is the -1m Z offset in the matrix all about? Seems like a latlong panorama would ignore the translation in any case, but why 1m?
> 
> https://github.com/aardvarkxr/aardvark/blob/ac7bc44d8af54553abc42f39917b43464af7ae2c/src/avrenderer/vrmanager.h#L58

that was just to position the quad in front of you, there's no reasoning behind the 1 meter aside from it was a number that was in front of the hmd / did not show edges.

**Comment by fuag15** [comment]
what a journey... turns out glm::perspective takes radians when the force radian define is set. Put in a pr to fix this
