### ISSUE TITLE
Panels not working on computers with multiple graphics cards (laptops)

### ISSUE THREAD

**Issue by zite** [aardvarkxr/aardvark#67]
After debugging with @JoeLudwig we decided that when creating the directx context it should probably specify a device.

https://github.com/aardvarkxr/aardvark/blob/master/src/avrenderer/av_cef_app.cpp#L98

**Comment by JoeLudwig** [comment]
I think all it'll take to get Aardvark running on laptops, without NVIDIA control panel shenanigans, is to make sure the DX device created in av_cef_app.cpp is created on the right GPU. There's an OpenVR call to tell you which adapter to create the device on, I just haven't hooked it up.
