### ISSUE TITLE
Installed Gadgets should be able to run without relaunch

### ISSUE THREAD

**Issue by forestgibson** [aardvarkxr/aardvark#69]
Currently, aardvark needs to be closed and relaunched to be able to run a newly installed gadget. 

Ideally, a gadget can be installed and then run while aardvark is running. If the app is set to automatically run in the manifest, then the gadget should run immediately after being installed.

**Comment by JoeLudwig** [comment]
Is this just the case for autorun gadgets? I think gadgets appear in the gadget menu without a restart...

**Comment by forestgibson** [comment]
I just tried with 2 different gadgets and for each one they didn't show up in the launcher or autolaunched when installed while aardvark was running. Closing and re-running aardvark resolved this issue.

**Comment by fuag15** [comment]
did a little bit of investigation into this, gadgets get parsed on initial load of the main panel gadget but never refresh when a new one is installed, would be helpful to have a shouldertap to that gadget when the list of installed gadgets change

**Comment by JoeLudwig** [comment]
I think this is irrelevant now with the switch to favorited gadgets instead of installed gadgets. Favorites can definitely be added while Aardvark is up and running.
