### ISSUE TITLE
AvGrabButton highlight and onTrigger not working with models

### ISSUE THREAD

**Issue by sophiabaldonado** [aardvarkxr/aardvark#77]
When using a local model in the `uri` prop using `AvGrabButton`, the model is rendered in the correct position but the highlight effect and the onTrigger do not work when hovering and pulling the trigger with the controller.

Note: I experienced this bug with the placeholder.glb and with my custom glTF model, but using `g_builtinModelGear` worked as expected. Also, my `AvGrabButton` was wrapped in a `AvTransform` with a specified position.

**Comment by JoeLudwig** [comment]
I believe this is fixed now. If you're still seeing it, please paste the gadget react node hierarchy you're generating into the bug so I can see what is different in your case.
