### ISSUE TITLE
Use of win32 shared memory vulkan extension blocks amd devices

### ISSUE THREAD

**Issue by fuag15** [aardvarkxr/aardvark#79]
Amd drivers don't support this extension. Noticed this yesterday but have yet to investigate alternatives.

**Comment by JoeLudwig** [comment]
Importing DXGI textures is pretty important. It's a feature of Vulkan 1.1, but maybe AMD has implemented that bit yet?

Or maybe this lingering bit of the older NV extension is messing things up?

			VkDedicatedAllocationImageCreateInfoNV dedicatedAllocationImageCreateInfo = { VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV };
			if ( externalImageFormatProperties.externalMemoryProperties.externalMemoryFeatures & VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT )
			{
				externalCreateInfo.pNext = &dedicatedAllocationImageCreateInfo;
				dedicatedAllocationImageCreateInfo.dedicatedAllocation = VK_TRUE;
			}

This code was adapted from an example that used the NVIDIA extension and switched over to the Vulkan 1.1 stuff in the process. Looks like I missed this one struct.

**Comment by fuag15** [comment]
roger. Thanks for the context, hope to have something soon

**Comment by fuag15** [comment]
This was a wild goose chase, the real error was the extra extensions being requested and I was misinterpreting the vkinfo command w.r.t. my gpu.
