### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by technobotanist** [aardvarkxr/aardvark#83]
When attempting to use init function in Aardvark CLI in powershell, a utility prompt returns. 

Simple answer is 'don't use powershell' but that could either be clarified in documentation or just made functional. 

![image](https://user-images.githubusercontent.com/42076090/72624628-4ef50b80-3915-11ea-803a-c687c6de9d2f.png)

**Comment by JoeLudwig** [comment]
Looks like @ is reserved in powershell. You're not running @aardvarkxr/init as a result.

You should just need to put @aardvarkxr in quotes:
![image](https://user-images.githubusercontent.com/303656/72668670-25ec7d80-39de-11ea-88ed-60c5f02ffad5.png)
