### ISSUE TITLE
There should be a way to have AVPanel have AVModel geometry. 

### ISSUE THREAD

**Issue by JaredMonkey** [aardvarkxr/aardvark#84]
It would be helpful for being able to render a 360 video.

**Comment by JoeLudwig** [comment]
360 video should probably be handled in its own thing, so I added #85 

Panels on arbitrary geometry is useful for other reasons, though. so let's keep this issue around to represent that.

One trick is that where 360 video probably doesn't need to be interactive, a panel wrapped around a watch face or some other geometry might.

**Comment by JoeLudwig** [comment]
AvPanel isn't a node type under the hood anymore. And you can put the panel texture on any model node. Take a look at the implementation of AvPanel for an example.
